name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  TEMP_PATH: /tmp/build
  WIN_TEMP_PATH: /tmp/winbuild

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install apt dependencies
      run: 'sudo apt-get update && sudo apt-get install -y cmake make git g++ python3 python3-pip mesa-common-dev libglu1-mesa-dev libsndfile-dev'

    - name: Install pip dependencies
      run: 'pip3 install -U pip && pip3 install aqtinstall'

    - name: Download AppImageKit
      run: 'wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage'

    - name: Create build path
      run: 'mkdir $TEMP_PATH'

    - name: Install Qt
      run: 'aqt install 5.14.2 linux desktop &&
            cp -r 5.14.2/gcc_64/* $TEMP_PATH'

    - name: Install libcorrect
      run: 'git clone https://github.com/quiet/libcorrect &&
            cd libcorrect &&
            mkdir build &&
            cd build &&
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TEMP_PATH .. &&
            make -j4 &&
            make install'

    - name: Compile LeanHRPT
      run: 'mkdir build &&
            cd build &&
            cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$TEMP_PATH -DWAR_CRIMES=1 .. &&
            make -j4'

    - name: Package
      run: 'mkdir LeanHRPT-Demod.AppDir &&
            mkdir LeanHRPT-Demod.AppDir/usr &&
            mkdir LeanHRPT-Demod.AppDir/usr/bin &&
            mkdir LeanHRPT-Demod.AppDir/usr/lib &&
            mkdir LeanHRPT-Demod.AppDir/usr/plugins &&
            cp AppRun                            LeanHRPT-Demod.AppDir/ &&
            cp LeanHRPT-Demod.desktop            LeanHRPT-Demod.AppDir/ &&
            cp logo128.png                       LeanHRPT-Demod.AppDir/ &&
            cp -r $TEMP_PATH/plugins/platforms/  LeanHRPT-Demod.AppDir/usr/plugins/ &&
            cp $TEMP_PATH/lib/libQt5Gui.so.5     LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libQt5Widgets.so.5 LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libQt5Core.so.5    LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libQt5XcbQpa.so.5  LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libQt5DBus.so.5    LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libicuuc.so.56     LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libicui18n.so.56   LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libicudata.so.56   LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp $TEMP_PATH/lib/libcorrect.so      LeanHRPT-Demod.AppDir/usr/lib/ &&
            cp build/LeanHRPT-Demod              LeanHRPT-Demod.AppDir/usr/bin/ &&
            ./appimagetool-x86_64.AppImage LeanHRPT-Demod.AppDir'

    - uses: actions/upload-artifact@v2
      with:
        name: LeanHRPT_Demod-x86_64.AppImage
        path: ./LeanHRPT_Demod-x86_64.AppImage

  build_windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install apt dependencies
      run: 'sudo apt-get update && sudo apt-get install -y cmake make git python3 python3-pip mingw-w64 zip'

    - name: Install pip dependencies
      run: 'pip3 install -U pip && pip3 install aqtinstall'

    - name: Create build path
      run: 'mkdir $TEMP_PATH && mkdir $WIN_TEMP_PATH'

    - name: Install Qt
      run: 'aqt install 5.14.2 linux desktop &&
            aqt install 5.14.2 windows desktop win64_mingw73 || true &&
            cp -r 5.14.2/gcc_64/* $TEMP_PATH &&
            cp -r 5.14.2/mingw73_64/* $WIN_TEMP_PATH'

    - name: Patch Qt
      run: 'rm $WIN_TEMP_PATH/bin/moc.exe &&
            ln -s $TEMP_PATH/bin/moc $WIN_TEMP_PATH/bin/moc.exe &&
            rm $WIN_TEMP_PATH/bin/rcc.exe &&
            ln -s $TEMP_PATH/bin/rcc $WIN_TEMP_PATH/bin/rcc.exe &&
            rm $WIN_TEMP_PATH/bin/uic.exe &&
            ln -s $TEMP_PATH/bin/uic $WIN_TEMP_PATH/bin/uic.exe'
    
    - name: Install libcorrect
      run: 'git clone https://github.com/quiet/libcorrect &&
            cd libcorrect &&
            mkdir build &&
            cd build &&
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-x86_64.cmake -DCMAKE_INSTALL_PREFIX=$WIN_TEMP_PATH .. &&
            make -j4 &&
            make install'

    - name: Install libsndfile
      run: 'wget https://github.com/erikd/libsndfile/releases/download/v1.0.29/libsndfile-1.0.29-win64.zip &&
            unzip libsndfile-1.0.29-win64.zip &&
            cp "libsndfile-1.0.29-win64/bin/sndfile.dll"   $WIN_TEMP_PATH/bin/sndfile.dll &&
            cp "libsndfile-1.0.29-win64/include/sndfile.h" $WIN_TEMP_PATH/include/sndfile.h &&
            cp "libsndfile-1.0.29-win64/lib/sndfile.lib"   $WIN_TEMP_PATH/lib/sndfile.lib'

    - name: Compile LeanHRPT
      run: 'mkdir build &&
            cd build &&
            cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-x86_64.cmake -DCMAKE_INSTALL_PREFIX=$WIN_TEMP_PATH -DWAR_CRIMES=1 .. &&
            make -j4'

    - name: Package
      run: 'mkdir LeanHRPT-Demod &&
            mkdir LeanHRPT-Demod/plugins &&
            mkdir LeanHRPT-Demod/plugins/styles &&
            mkdir LeanHRPT-Demod/platforms &&
            cp logo128.png                                             LeanHRPT-Demod/ &&
            cp build/LeanHRPT-Demod.exe                                LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/bin/Qt5Core.dll                          LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/bin/Qt5Gui.dll                           LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/bin/Qt5Widgets.dll                       LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/lib/libcorrect.dll                       LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/bin/libgcc_s_seh-1.dll                   LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/bin/libstdc++-6.dll                      LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/bin/libwinpthread-1.dll                  LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/bin/sndfile.dll                          LeanHRPT-Demod/ &&
            cp /usr/lib/gcc/x86_64-w64-mingw32/9.3-win32/libgomp-1.dll LeanHRPT-Demod/ &&
            cp $WIN_TEMP_PATH/plugins/styles/qwindowsvistastyle.dll    LeanHRPT-Demod/plugins/styles/ &&
            cp $WIN_TEMP_PATH/plugins/platforms/qwindows.dll           LeanHRPT-Demod/platforms/ &&
            zip -r LeanHRPT-Demod.zip LeanHRPT-Demod/'

    - uses: actions/upload-artifact@v2
      with:
        name: LeanHRPT_Demod-x86_64-w64
        path: ./LeanHRPT-Demod.zip
